# Form implementation generated from reading ui file 'dialogPresupuesto.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialogPresupuesto(object):
    def setupUi(self, dialogPresupuesto):
        dialogPresupuesto.setObjectName("dialogPresupuesto")
        dialogPresupuesto.resize(483, 284)
        dialogPresupuesto.setStyleSheet("QPushButton {\n"
"    background-color: rgb(80, 99, 191);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(80, 99, 191);\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QPushButton:clicked{\n"
"    background-color: rgb(65, 84, 176);\n"
"    border: 2px solid rgb(65, 84, 176);\n"
"}\n"
"\n"
"\n"
"QDialog {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QComboBox, QDateEdit, QDoubleSpinBox, QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 3px;\n"
"    background-color: white;\n"
"    padding: 1px 18px 1px 3px;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox:on\n"
"{\n"
"    padding-top: 0px;\n"
"    padding-left: 0px;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: white;\n"
"    color: black;\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: white;\n"
"    color:black;\n"
"}\n"
"\n"
"\n"
"#btnEliminar {\n"
"    background-color: #e74c3c;\n"
"    border: 2px solid #e74c3c;\n"
"}\n"
"\n"
"#btnEliminar:hover {\n"
"    background-color: #c0392b;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(60, 60, 60);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-bottom: 2px solid rgb(103, 129, 255);\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(dialogPresupuesto)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=dialogPresupuesto)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cmbCategoria = QtWidgets.QComboBox(parent=dialogPresupuesto)
        self.cmbCategoria.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cmbCategoria.setFont(font)
        self.cmbCategoria.setObjectName("cmbCategoria")
        self.horizontalLayout.addWidget(self.cmbCategoria)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=dialogPresupuesto)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.dsbMontoObjetivo = QtWidgets.QDoubleSpinBox(parent=dialogPresupuesto)
        self.dsbMontoObjetivo.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.dsbMontoObjetivo.setFont(font)
        self.dsbMontoObjetivo.setMaximum(999999.0)
        self.dsbMontoObjetivo.setSingleStep(0.5)
        self.dsbMontoObjetivo.setObjectName("dsbMontoObjetivo")
        self.horizontalLayout_2.addWidget(self.dsbMontoObjetivo)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 1, 1, 1)
        self.btnCancelar = QtWidgets.QPushButton(parent=dialogPresupuesto)
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        font.setPointSize(12)
        font.setBold(False)
        self.btnCancelar.setFont(font)
        self.btnCancelar.setObjectName("btnCancelar")
        self.gridLayout.addWidget(self.btnCancelar, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnEliminar = QtWidgets.QPushButton(parent=dialogPresupuesto)
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        font.setPointSize(12)
        font.setBold(False)
        self.btnEliminar.setFont(font)
        self.btnEliminar.setObjectName("btnEliminar")
        self.horizontalLayout_3.addWidget(self.btnEliminar)
        self.btnGuardar = QtWidgets.QPushButton(parent=dialogPresupuesto)
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        font.setPointSize(12)
        font.setBold(False)
        self.btnGuardar.setFont(font)
        self.btnGuardar.setObjectName("btnGuardar")
        self.horizontalLayout_3.addWidget(self.btnGuardar)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 1, 2, 2)
        spacerItem6 = QtWidgets.QSpacerItem(24, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 1, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(24, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 2, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem8, 3, 2, 1, 1)

        self.retranslateUi(dialogPresupuesto)
        QtCore.QMetaObject.connectSlotsByName(dialogPresupuesto)

    def retranslateUi(self, dialogPresupuesto):
        _translate = QtCore.QCoreApplication.translate
        dialogPresupuesto.setWindowTitle(_translate("dialogPresupuesto", "Presupuesto"))
        self.label.setText(_translate("dialogPresupuesto", "Categoria:"))
        self.label_2.setText(_translate("dialogPresupuesto", "Monto objetivo:"))
        self.btnCancelar.setText(_translate("dialogPresupuesto", "Cancelar"))
        self.btnEliminar.setText(_translate("dialogPresupuesto", "Eliminar"))
        self.btnGuardar.setText(_translate("dialogPresupuesto", "Guardar"))
