# Form implementation generated from reading ui file 'RegisterView.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(855, 562)
        Register.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"QPushButton#btnIniciarSesion{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    text-align: center; \n"
"    padding: 0px; \n"
"}\n"
"\n"
"QPushButton#btnIniciarSesion:hover {\n"
"            text-decoration: underline; /* Optional: Add underline on hover */\n"
"}\n"
"\n"
"QPushButton#btnIniciarSesion:pressed {\n"
"            color: gray; /* Optional: Change color on click */\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color:gray;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(80, 99, 191);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(80, 99, 191);\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(60, 60, 60);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-bottom: 2px solid rgb(103, 129, 255);\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QPushButton:clicked{\n"
"    background-color: rgb(65, 84, 176);\n"
"    border: 2px solid rgb(65, 84, 176);\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=Register)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 4, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(272, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lblRegistro = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setKerning(True)
        self.lblRegistro.setFont(font)
        self.lblRegistro.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblRegistro.setObjectName("lblRegistro")
        self.verticalLayout_8.addWidget(self.lblRegistro)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblNombre = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        font.setPointSize(12)
        self.lblNombre.setFont(font)
        self.lblNombre.setStyleSheet("")
        self.lblNombre.setObjectName("lblNombre")
        self.verticalLayout_2.addWidget(self.lblNombre)
        self.txtNombre = QtWidgets.QLineEdit(parent=self.widget)
        self.txtNombre.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        font.setPointSize(12)
        self.txtNombre.setFont(font)
        self.txtNombre.setObjectName("txtNombre")
        self.verticalLayout_2.addWidget(self.txtNombre)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblApellido = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        font.setPointSize(12)
        self.lblApellido.setFont(font)
        self.lblApellido.setStyleSheet("")
        self.lblApellido.setObjectName("lblApellido")
        self.verticalLayout.addWidget(self.lblApellido)
        self.txtApellido = QtWidgets.QLineEdit(parent=self.widget)
        self.txtApellido.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        font.setPointSize(12)
        self.txtApellido.setFont(font)
        self.txtApellido.setObjectName("txtApellido")
        self.verticalLayout.addWidget(self.txtApellido)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblNombreUsuario = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        font.setPointSize(12)
        self.lblNombreUsuario.setFont(font)
        self.lblNombreUsuario.setStyleSheet("")
        self.lblNombreUsuario.setObjectName("lblNombreUsuario")
        self.verticalLayout_3.addWidget(self.lblNombreUsuario)
        self.txtNombreUsuario = QtWidgets.QLineEdit(parent=self.widget)
        self.txtNombreUsuario.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        font.setPointSize(12)
        self.txtNombreUsuario.setFont(font)
        self.txtNombreUsuario.setObjectName("txtNombreUsuario")
        self.verticalLayout_3.addWidget(self.txtNombreUsuario)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblCorreo = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        font.setPointSize(12)
        self.lblCorreo.setFont(font)
        self.lblCorreo.setStyleSheet("")
        self.lblCorreo.setObjectName("lblCorreo")
        self.verticalLayout_4.addWidget(self.lblCorreo)
        self.txtCorreo = QtWidgets.QLineEdit(parent=self.widget)
        self.txtCorreo.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        font.setPointSize(12)
        self.txtCorreo.setFont(font)
        self.txtCorreo.setObjectName("txtCorreo")
        self.verticalLayout_4.addWidget(self.txtCorreo)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblPassword = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        font.setPointSize(12)
        self.lblPassword.setFont(font)
        self.lblPassword.setStyleSheet("")
        self.lblPassword.setObjectName("lblPassword")
        self.verticalLayout_5.addWidget(self.lblPassword)
        self.txtPassword = QtWidgets.QLineEdit(parent=self.widget)
        self.txtPassword.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        font.setPointSize(12)
        self.txtPassword.setFont(font)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.verticalLayout_5.addWidget(self.txtPassword)
        self.cbxMostrarPassword = QtWidgets.QCheckBox(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cbxMostrarPassword.setFont(font)
        self.cbxMostrarPassword.setObjectName("cbxMostrarPassword")
        self.verticalLayout_5.addWidget(self.cbxMostrarPassword)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lblConfirmaPassword = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        font.setPointSize(12)
        self.lblConfirmaPassword.setFont(font)
        self.lblConfirmaPassword.setStyleSheet("")
        self.lblConfirmaPassword.setObjectName("lblConfirmaPassword")
        self.verticalLayout_6.addWidget(self.lblConfirmaPassword)
        self.txtConfirmaPassword = QtWidgets.QLineEdit(parent=self.widget)
        self.txtConfirmaPassword.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        font.setPointSize(12)
        self.txtConfirmaPassword.setFont(font)
        self.txtConfirmaPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtConfirmaPassword.setObjectName("txtConfirmaPassword")
        self.verticalLayout_6.addWidget(self.txtConfirmaPassword)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.btnRegistrarse = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        font.setPointSize(12)
        font.setBold(False)
        self.btnRegistrarse.setFont(font)
        self.btnRegistrarse.setObjectName("btnRegistrarse")
        self.verticalLayout_7.addWidget(self.btnRegistrarse)
        self.btnIniciarSesion = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnIniciarSesion.setFont(font)
        self.btnIniciarSesion.setObjectName("btnIniciarSesion")
        self.verticalLayout_7.addWidget(self.btnIniciarSesion)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.gridLayout.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(272, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 4, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 2, 1, 1, 1)
        Register.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Register)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 855, 24))
        self.menubar.setObjectName("menubar")
        Register.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Register)
        self.statusbar.setObjectName("statusbar")
        Register.setStatusBar(self.statusbar)

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)
        Register.setTabOrder(self.txtNombre, self.txtApellido)
        Register.setTabOrder(self.txtApellido, self.txtNombreUsuario)
        Register.setTabOrder(self.txtNombreUsuario, self.txtCorreo)
        Register.setTabOrder(self.txtCorreo, self.txtPassword)
        Register.setTabOrder(self.txtPassword, self.cbxMostrarPassword)
        Register.setTabOrder(self.cbxMostrarPassword, self.txtConfirmaPassword)
        Register.setTabOrder(self.txtConfirmaPassword, self.btnRegistrarse)
        Register.setTabOrder(self.btnRegistrarse, self.btnIniciarSesion)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Registro - Asistente Financiero Personal"))
        self.lblRegistro.setText(_translate("Register", "Registrate"))
        self.lblNombre.setText(_translate("Register", "Nombre:"))
        self.lblApellido.setText(_translate("Register", "Apellido:"))
        self.lblNombreUsuario.setText(_translate("Register", "Nombre de usuario:"))
        self.lblCorreo.setText(_translate("Register", "Correo electronico:"))
        self.lblPassword.setText(_translate("Register", "Contrasena:"))
        self.cbxMostrarPassword.setText(_translate("Register", "Mostrar contrasena"))
        self.lblConfirmaPassword.setText(_translate("Register", "Confirmar contrasena:"))
        self.btnRegistrarse.setText(_translate("Register", "Registrarse"))
        self.btnIniciarSesion.setText(_translate("Register", "Si ya tienes una cuenta. Inicia sesion."))
