# Form implementation generated from reading ui file 'DialogTransaccion.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialogTransaccion(object):
    def setupUi(self, dialogTransaccion):
        dialogTransaccion.setObjectName("dialogTransaccion")
        dialogTransaccion.resize(520, 536)
        dialogTransaccion.setStyleSheet("QPushButton {\n"
"    background-color: rgb(80, 99, 191);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(80, 99, 191);\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QPushButton:clicked{\n"
"    background-color: rgb(65, 84, 176);\n"
"    border: 2px solid rgb(65, 84, 176);\n"
"}\n"
"\n"
"\n"
"QDialog {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QComboBox, QDateEdit, QDoubleSpinBox, QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 3px;\n"
"    background-color: white;\n"
"    padding: 1px 18px 1px 3px;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox:on\n"
"{\n"
"    padding-top: 0px;\n"
"    padding-left: 0px;\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: white;\n"
"    color: black;\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: white;\n"
"    color:black;\n"
"}\n"
"\n"
"\n"
"#btnEliminar {\n"
"    background-color: #e74c3c;\n"
"    border: 2px solid #e74c3c;\n"
"}\n"
"\n"
"#btnEliminar:hover {\n"
"    background-color: #c0392b;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(60, 60, 60);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-bottom: 2px solid rgb(103, 129, 255);\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(dialogTransaccion)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(19, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=dialogTransaccion)
        self.label.setMinimumSize(QtCore.QSize(160, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.cmbTipoTransaccion = QtWidgets.QComboBox(parent=dialogTransaccion)
        self.cmbTipoTransaccion.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cmbTipoTransaccion.setFont(font)
        self.cmbTipoTransaccion.setObjectName("cmbTipoTransaccion")
        self.cmbTipoTransaccion.addItem("")
        self.cmbTipoTransaccion.addItem("")
        self.horizontalLayout_2.addWidget(self.cmbTipoTransaccion)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=dialogTransaccion)
        self.label_2.setMinimumSize(QtCore.QSize(160, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.dsbMonto = QtWidgets.QDoubleSpinBox(parent=dialogTransaccion)
        self.dsbMonto.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.dsbMonto.setFont(font)
        self.dsbMonto.setMaximum(999999.0)
        self.dsbMonto.setSingleStep(0.5)
        self.dsbMonto.setObjectName("dsbMonto")
        self.horizontalLayout_3.addWidget(self.dsbMonto)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=dialogTransaccion)
        self.label_3.setMinimumSize(QtCore.QSize(160, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.dateTransaccion = QtWidgets.QDateEdit(parent=dialogTransaccion)
        self.dateTransaccion.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateTransaccion.setFont(font)
        self.dateTransaccion.setCurrentSection(QtWidgets.QDateTimeEdit.Section.YearSection)
        self.dateTransaccion.setCalendarPopup(False)
        self.dateTransaccion.setObjectName("dateTransaccion")
        self.horizontalLayout_4.addWidget(self.dateTransaccion)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=dialogTransaccion)
        self.label_4.setMinimumSize(QtCore.QSize(160, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.cmbCategoria = QtWidgets.QComboBox(parent=dialogTransaccion)
        self.cmbCategoria.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cmbCategoria.setFont(font)
        self.cmbCategoria.setObjectName("cmbCategoria")
        self.horizontalLayout_5.addWidget(self.cmbCategoria)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(parent=dialogTransaccion)
        self.label_5.setMinimumSize(QtCore.QSize(160, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.txtDescripcion = QtWidgets.QLineEdit(parent=dialogTransaccion)
        self.txtDescripcion.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtDescripcion.setFont(font)
        self.txtDescripcion.setObjectName("txtDescripcion")
        self.horizontalLayout_6.addWidget(self.txtDescripcion)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem11 = QtWidgets.QSpacerItem(20, 70, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem11)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem12, 0, 1, 1, 1)
        self.btnCancelar = QtWidgets.QPushButton(parent=dialogTransaccion)
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        font.setPointSize(12)
        font.setBold(False)
        self.btnCancelar.setFont(font)
        self.btnCancelar.setObjectName("btnCancelar")
        self.gridLayout.addWidget(self.btnCancelar, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnEliminar = QtWidgets.QPushButton(parent=dialogTransaccion)
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        font.setPointSize(12)
        font.setBold(False)
        self.btnEliminar.setFont(font)
        self.btnEliminar.setObjectName("btnEliminar")
        self.horizontalLayout.addWidget(self.btnEliminar)
        self.btnGuardar = QtWidgets.QPushButton(parent=dialogTransaccion)
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        font.setPointSize(12)
        font.setBold(False)
        self.btnGuardar.setFont(font)
        self.btnGuardar.setObjectName("btnGuardar")
        self.horizontalLayout.addWidget(self.btnGuardar)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(19, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem13, 1, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem14, 2, 1, 1, 1)

        self.retranslateUi(dialogTransaccion)
        QtCore.QMetaObject.connectSlotsByName(dialogTransaccion)

    def retranslateUi(self, dialogTransaccion):
        _translate = QtCore.QCoreApplication.translate
        dialogTransaccion.setWindowTitle(_translate("dialogTransaccion", "Dialog"))
        self.label.setText(_translate("dialogTransaccion", "Tipo de transaccion:"))
        self.cmbTipoTransaccion.setItemText(0, _translate("dialogTransaccion", "dfasf"))
        self.cmbTipoTransaccion.setItemText(1, _translate("dialogTransaccion", "fdsa"))
        self.label_2.setText(_translate("dialogTransaccion", "Monto:"))
        self.label_3.setText(_translate("dialogTransaccion", "Fecha:"))
        self.dateTransaccion.setDisplayFormat(_translate("dialogTransaccion", "yyyy/dd/MM"))
        self.label_4.setText(_translate("dialogTransaccion", "Categoria:"))
        self.label_5.setText(_translate("dialogTransaccion", "Descripcion:"))
        self.btnCancelar.setText(_translate("dialogTransaccion", "Cancelar"))
        self.btnEliminar.setText(_translate("dialogTransaccion", "Eliminar"))
        self.btnGuardar.setText(_translate("dialogTransaccion", "Guardar"))
