# Form implementation generated from reading ui file 'LoginView.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(861, 544)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(False)
        Login.setFont(font)
        Login.setAcceptDrops(True)
        Login.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"QPushButton#btnRegistrarse{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    text-align: center; \n"
"    padding: 0px; \n"
"}\n"
"\n"
"QPushButton#btnRegistrarse:hover {\n"
"            text-decoration: underline; /* Optional: Add underline on hover */\n"
"}\n"
"\n"
"QPushButton#btnRegistrarse:pressed {\n"
"            color: gray; /* Optional: Change color on click */\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color:gray;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(80, 99, 191);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(80, 99, 191);\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(60, 60, 60);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-bottom: 2px solid rgb(103, 129, 255);\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QPushButton:clicked{\n"
"    background-color: rgb(65, 84, 176);\n"
"    border: 2px solid rgb(65, 84, 176);\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=Login)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 23, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(227, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 19, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblBienvenido = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setKerning(True)
        self.lblBienvenido.setFont(font)
        self.lblBienvenido.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblBienvenido.setObjectName("lblBienvenido")
        self.verticalLayout_4.addWidget(self.lblBienvenido)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 40, -1, 30)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblNombreUsuario = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        font.setPointSize(12)
        self.lblNombreUsuario.setFont(font)
        self.lblNombreUsuario.setStyleSheet("")
        self.lblNombreUsuario.setObjectName("lblNombreUsuario")
        self.verticalLayout.addWidget(self.lblNombreUsuario)
        self.txtNombreUsuario = QtWidgets.QLineEdit(parent=self.widget)
        self.txtNombreUsuario.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        font.setPointSize(12)
        self.txtNombreUsuario.setFont(font)
        self.txtNombreUsuario.setObjectName("txtNombreUsuario")
        self.verticalLayout.addWidget(self.txtNombreUsuario)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblPassword = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        font.setPointSize(12)
        self.lblPassword.setFont(font)
        self.lblPassword.setObjectName("lblPassword")
        self.verticalLayout_2.addWidget(self.lblPassword)
        self.txtPassword = QtWidgets.QLineEdit(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        font.setPointSize(12)
        self.txtPassword.setFont(font)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.verticalLayout_2.addWidget(self.txtPassword)
        self.cbxMostrarPassword = QtWidgets.QCheckBox(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cbxMostrarPassword.setFont(font)
        self.cbxMostrarPassword.setObjectName("cbxMostrarPassword")
        self.verticalLayout_2.addWidget(self.cbxMostrarPassword)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.btnIniciarSesion = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Adwaita Sans")
        font.setPointSize(12)
        font.setBold(False)
        self.btnIniciarSesion.setFont(font)
        self.btnIniciarSesion.setObjectName("btnIniciarSesion")
        self.verticalLayout_4.addWidget(self.btnIniciarSesion)
        self.btnRegistrarse = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnRegistrarse.setFont(font)
        self.btnRegistrarse.setObjectName("btnRegistrarse")
        self.verticalLayout_4.addWidget(self.btnRegistrarse)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 2, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(226, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 23, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 2, 1, 1, 1)
        Login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 861, 24))
        self.menubar.setObjectName("menubar")
        Login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Asistente Financiero Personal"))
        self.lblBienvenido.setText(_translate("Login", "Bienvenido"))
        self.lblNombreUsuario.setText(_translate("Login", "Nombre de usuario:"))
        self.lblPassword.setText(_translate("Login", "Contraseña:"))
        self.cbxMostrarPassword.setText(_translate("Login", "Mostrar contrasena"))
        self.btnIniciarSesion.setText(_translate("Login", "Iniciar sesion"))
        self.btnRegistrarse.setText(_translate("Login", "Si aun no tienes una cuenta. Registrate"))
